name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install BUILD-UTILS
      run:  sudo apt-get -y install build-essential libfl-dev
    - name: make
      run: make
